config.code=2312
config.username=admin1
config.message=Standar message
config.listOfValues=value1,value2,value3
config.valuesMap={product: 'laptop i3', description: 'laptop i3 description', price: 1200.00}